package com.rescript.plugin.flow

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Drives [MermaidSourceColorizer]'s pure rendering helpers without an
 * [com.intellij.openapi.editor.colors.EditorColorsManager] fixture.
 * Concrete CSS values are hand-fed so the tests assert structural
 * properties (which tokens get wrapped, which lines are skipped) and
 * not colours, which would be scheme-dependent.
 */
class MermaidSourceColorizerTest {
    private val keyword = "#111111"
    private val operator = "#222222"
    private val string = "#333333"
    private val comment = "#444444"

    @Test
    fun `renderLine wraps the flowchart keyword in the keyword colour`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "flowchart TD",
                keyword,
                operator,
                string,
                comment,
            )
        assertTrue(html.contains("color:$keyword"), "expected keyword colour, got $html")
        assertTrue(html.contains("flowchart"), "keyword text must appear in $html")
        assertTrue(html.contains("TD"), "direction keyword must appear in $html")
    }

    @Test
    fun `renderLine wraps the arrow operator in the operator colour`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "  A --> B",
                keyword,
                operator,
                string,
                comment,
            )
        assertTrue(html.contains("color:$operator"), "expected operator colour for arrow, got $html")
        // The "-->" arrow should be HTML-escaped to "--&gt;" inside a coloured span.
        assertTrue(html.contains("--&gt;"), "arrow should be HTML-escaped in $html")
    }

    @Test
    fun `renderLine wraps quoted node labels in the string colour`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "n0[\"Some(_)\"]",
                keyword,
                operator,
                string,
                comment,
            )
        assertTrue(html.contains("color:$string"), "expected string colour for quoted label, got $html")
        // The literal pattern text should survive, with HTML-escaped quotes.
        assertTrue(html.contains("Some(_)"), "label content must be preserved in $html")
    }

    @Test
    fun `renderLine paints entire comment lines in the comment colour`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "%% Generated by RescriptVariantFlowMermaidExporter",
                keyword,
                operator,
                string,
                comment,
            )
        assertTrue(html.contains("color:$comment"), "expected comment colour, got $html")
        assertFalse(html.contains("color:$keyword"), "comment line must not contain keyword colour")
    }

    @Test
    fun `renderLine leaves plain text untouched`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "    n0",
                keyword,
                operator,
                string,
                comment,
            )
        assertFalse(html.contains("color:"), "plain text line must not contain any coloured span, got $html")
        assertEquals("    n0", html)
    }

    @Test
    fun `renderWithColors wraps the whole document in html body tags`() {
        val source = "flowchart TD\n  A --> B\n"
        val html =
            MermaidSourceColorizer.renderWithColors(
                source,
                keyword,
                operator,
                string,
                comment,
            )
        assertTrue(html.startsWith("<html>"), "expected html wrapper, got $html")
        assertTrue(html.contains("flowchart"), "first line keyword must appear")
        assertTrue(html.contains("--&gt;"), "second line arrow must appear")
        assertTrue(html.contains("<br>"), "line breaks must be preserved")
    }

    @Test
    fun `renderLine escapes HTML metacharacters in plain text portions`() {
        val html =
            MermaidSourceColorizer.renderLine(
                "x < y",
                keyword,
                operator,
                string,
                comment,
            )
        // `<` outside a recognised token should be escaped to `&lt;`
        assertTrue(html.contains("&lt;"), "less-than must be escaped in $html")
    }
}
