package com.rescript.plugin.wizard.templates

import com.rescript.plugin.wizard.PackageManager
import com.rescript.plugin.wizard.ProjectFileBuilders
import com.rescript.plugin.wizard.ValidationLibrary

/**
 * Generates project template files for a Tauri 2.x desktop application powered by ReScript and Vite+.
 *
 * Pairs a Tauri Rust process (in `src-tauri/`) with a Vite+ renderer that bundles the React UI
 * written in ReScript. The IPC bridge is `@rescript-tauri/core`'s `Core.Raw.invoke`, and renderer
 * code validates command responses through `Validation.res` — either zod or sury, selected via
 * [TemplateContext.validationLibrary] — so a Rust struct that drifts from the ReScript record
 * surfaces as a UI error instead of a silent type crash.
 */
internal object TauriTemplateFiles {
    private const val RESOURCE_ROOT = "tauri"

    private val SRC_TAURI_GITIGNORE =
        """
        # Generated by Cargo
        target/

        # Generated bundle artifacts (Tauri build output)
        gen/
        """.trimIndent() + "\n"

    /**
     * Generates Tauri template files using the supplied [TemplateContext].
     *
     * The `tauri.conf.json` is rendered with package-manager-aware `beforeDevCommand` /
     * `beforeBuildCommand` strings (e.g. `pnpm dev` vs `npm run dev`) so `tauri dev` and
     * `tauri build` invoke the user-selected script runner without further configuration.
     */
    fun generate(ctx: TemplateContext): Map<String, String> {
        val projectVars = mapOf("projectName" to ctx.projectName)
        val tauriConfVars =
            mapOf(
                "projectName" to ctx.projectName,
                "cmdRunDev" to ctx.runCmd("dev"),
                "cmdBuild" to ctx.runCmd("build"),
            )
        val variantKey = ctx.validationLibrary.variantKey()
        return mapOf(
            "rescript.json" to
                ProjectFileBuilders.rescriptJson(
                    name = ctx.projectName,
                    bsDependencies =
                        listOf("@rescript/core", "@rescript/react", "@rescript-tauri/core") +
                            ctx.validationBsDeps(),
                    includeJsx = true,
                ),
            "package.json" to
                ProjectFileBuilders.packageJson(
                    name = ctx.projectName,
                    isPrivate = true,
                    type = "module",
                    packageManager = ctx.packageManagerSpec(),
                    engines = mapOf("node" to ctx.nodeEngine),
                    dependencies = tauriDependencies(ctx.validationLibrary),
                    devDependencies =
                        linkedMapOf(
                            "@tauri-apps/cli" to TemplateVersions.TAURI_APPS_CLI,
                            "@vitejs/plugin-react" to TemplateVersions.VITEJS_PLUGIN_REACT,
                            "vite" to TemplateVersions.VITE,
                            "vite-plus" to TemplateVersions.VITE_PLUS,
                            "@voidzero-dev/vite-plus-core" to TemplateVersions.VITE_PLUS_CORE,
                            "vitest" to TemplateVersions.VITEST,
                            "@vitest/coverage-v8" to TemplateVersions.VITEST_COVERAGE_V8,
                        ),
                    scripts =
                        linkedMapOf(
                            "dev" to "vp dev",
                            "build" to "vp build",
                            "tauri" to "tauri",
                            "tauri:dev" to "tauri dev",
                            "tauri:build" to "tauri build",
                            "test" to "vp test",
                            "test:coverage" to "vp test --coverage",
                            "res:build" to "rescript",
                            "res:clean" to "rescript clean",
                            "res:dev" to "rescript -w",
                        ),
                ),
            "index.html" to TemplateResourceLoader.load("$RESOURCE_ROOT/index.html", projectVars),
            "vite.config.mjs" to TemplateResourceLoader.load("$RESOURCE_ROOT/vite.config.mjs"),
            "src/Main.res" to TemplateResourceLoader.load("$RESOURCE_ROOT/src/Main.res"),
            "src/App.res" to TemplateResourceLoader.load("$RESOURCE_ROOT/src/App.res"),
            "src/Tauri.res" to TemplateResourceLoader.load("$RESOURCE_ROOT/src/Tauri.res"),
            "src/Validation.res" to
                TemplateResourceLoader.load("$RESOURCE_ROOT/variants/$variantKey/src/Validation.res"),
            "src/__tests__/App.test.mjs" to
                TemplateResourceLoader.load("$RESOURCE_ROOT/src/__tests__/App.test.mjs"),
            "src-tauri/Cargo.toml" to
                TemplateResourceLoader.load("$RESOURCE_ROOT/src-tauri/Cargo.toml", projectVars),
            "src-tauri/build.rs" to TemplateResourceLoader.load("$RESOURCE_ROOT/src-tauri/build.rs"),
            "src-tauri/src/main.rs" to TemplateResourceLoader.load("$RESOURCE_ROOT/src-tauri/src/main.rs"),
            "src-tauri/tauri.conf.json" to
                TemplateResourceLoader.load("$RESOURCE_ROOT/src-tauri/tauri.conf.json", tauriConfVars),
            // .gitignore content is inlined rather than loaded from resources because
            // Gradle's default resources include rule filters out dotfile basenames.
            "src-tauri/.gitignore" to SRC_TAURI_GITIGNORE,
            "README.md" to
                CommonFiles.readme(
                    ctx = ctx,
                    description =
                        "A Tauri 2.x desktop app with a ReScript + React renderer bundled by Vite+. " +
                            "IPC payloads from Rust are validated in the renderer via " +
                            "${ctx.validationLibrary.displayName} before they reach UI code.",
                    scripts =
                        listOf(
                            "tauri:dev" to "Run the Tauri app (compiles Rust + starts the renderer)",
                            "tauri:build" to "Bundle a production binary (requires Rust + signing setup)",
                            "dev" to "Start the Vite+ dev server for the renderer only",
                            "build" to "Bundle the renderer for production",
                            "test" to "Run Vitest via Vite+",
                            "res:dev" to "Watch ReScript sources",
                        ),
                    extraPrerequisites =
                        listOf(
                            "Rust toolchain (`rustup default stable`) — needed for `tauri dev` / `tauri build`",
                            "Platform build deps for Tauri — see https://v2.tauri.app/start/prerequisites/",
                        ),
                    extraSections =
                        listOf(
                            "Renderer ↔ Rust IPC" to
                                TemplateResourceLoader.load("$RESOURCE_ROOT/readme/ipc.md"),
                            "Production Bundling" to
                                TemplateResourceLoader.load("$RESOURCE_ROOT/readme/production.md"),
                        ),
                ),
            ".nvmrc" to CommonFiles.nvmrc(ctx),
            "LICENSE" to CommonFiles.mitLicense(ctx, holder = ctx.projectName),
            ".github/dependabot.yml" to CommonFiles.dependabotYaml(),
            ".gitignore" to
                CommonFiles.gitignore(
                    extra =
                        listOf(
                            "dist/",
                            ".vite/",
                            // Rust build output also lives in src-tauri/.gitignore, but listing
                            // it here keeps a top-level checkout clean even if the inner
                            // .gitignore is removed.
                            "src-tauri/target/",
                            "src-tauri/gen/",
                        ),
                ),
            ".editorconfig" to CommonFiles.editorconfig(),
            ".github/workflows/ci.yml" to CommonFiles.ciWorkflow(ctx, hasBuild = true, hasTest = true),
        )
    }

    /**
     * Back-compatible entry point used by tests and any external callers.
     */
    fun generate(projectName: String): Map<String, String> = generate(TemplateContext(projectName, PackageManager.PNPM))

    private fun tauriDependencies(validationLibrary: ValidationLibrary): LinkedHashMap<String, String> {
        val deps = linkedMapOf<String, String>()
        deps["rescript"] = TemplateVersions.RESCRIPT
        deps["@rescript/core"] = TemplateVersions.RESCRIPT_CORE
        deps["@rescript/runtime"] = TemplateVersions.RESCRIPT_RUNTIME
        deps["@rescript/react"] = TemplateVersions.RESCRIPT_REACT
        deps["@rescript-tauri/core"] = TemplateVersions.RESCRIPT_TAURI_CORE
        deps["@tauri-apps/api"] = TemplateVersions.TAURI_APPS_API
        deps["react"] = TemplateVersions.REACT
        deps["react-dom"] = TemplateVersions.REACT_DOM
        when (validationLibrary) {
            ValidationLibrary.ZOD -> deps["zod"] = TemplateVersions.ZOD
            ValidationLibrary.SURY -> deps["sury"] = TemplateVersions.SURY
        }
        return deps
    }
}
