import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

// `routeTree.gen.ts` is regenerated by `@tanstack/router-plugin` whenever the
// files under `app/routes/` change. The first `vite dev` run produces it.
export function getRouter() {
  return createRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
